import React from 'react'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import Providers from './lib/Providers'
import RootHeader from '../components/header/RootHeader'
import { Layout } from 'antd'
import { Content, Header } from 'antd/es/layout/layout'
import RootFooter from '../components/footer/RootFooter'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

interface RootLayoutProps {
  children: React.ReactNode
}

function RootLayout({ children }: RootLayoutProps) {
  return (
    <Providers>
      <html lang="en">
        <body className={inter.className}>
          <Layout className='relative containers mx-auto'>
            <RootHeader></RootHeader>

            {children}
          </Layout>
            <RootFooter />
        </body>
      </html>
    </Providers>
  )
}

export default RootLayout
