
import { Inter } from "next/font/google";
import "src/app/globals.css";
import Providers from "../lib/Providers";
import { Metadata } from "next";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

interface RootLayoutProps {
  children: React.ReactNode;
}

function RootLayout({ children }: RootLayoutProps) {

  return (
    <Providers>
      <html lang="en">
        <body className={inter.className}>
          <div className="relative">{children}</div>
        </body>
      </html>
    </Providers>
  );
}

export default RootLayout;
