import React from "react";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "src/app/globals.css";
import Providers from "../lib/Providers";
import RootHeader from "../components/header/RootHeader";
import RootFooter from "../components/footer/RootFooter";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

interface RootLayoutProps {
  children: React.ReactNode;
  serviceType: React.ReactElement;
}

function RootLayout({ children, serviceType }: RootLayoutProps) {
  return (
    <Providers>
      <html lang="en">
        <body className={inter.className}>
          <div className="relative">{children}</div>
        </body>
      </html>
    </Providers>
  );
}

export default RootLayout;
