import React from "react";
import type { Metadata } from "next";
import RootHeader from "../../components/header/RootHeader";
import RootFooter from "../../components/footer/RootFooter";
import { useGetMyInfoQuery } from "../../redux/app/apis/authApi";
import VerifyUser from "../../components/auth/VerifyUser";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

interface RootLayoutProps {
  children: React.ReactNode;
  serviceType: React.ReactElement;
}

function RootLayout({ children, serviceType }: RootLayoutProps) {
  return (
    <>
      <div className="relative">
        <RootHeader></RootHeader>
        <br />
        {children}
      </div>

      <RootFooter />
    </>
  );
}

export default RootLayout;
