
import type { Metadata } from "next";
import RootHeader from "../../components/header/RootHeader";
import RootFooter from "../../components/footer/RootFooter"; 

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

interface RootLayoutProps {
  children: React.ReactNode;
}

function RootLayout({ children }: RootLayoutProps) {
  return (
    <>
      <div className="relative">
        <RootHeader></RootHeader>
        <br />
        {children}
      </div>

      <RootFooter />
    </>
  );
}

export default RootLayout;
